# SPDX-FileCopyrightText: Copyright (c) 2011-2025 Yegor Bugayenko
# SPDX-License-Identifier: MIT
---
# yamllint disable rule:line-length
name: codecov
'on':
  push:
    branches:
      - master
jobs:
  codecov:
    timeout-minutes: 15
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: 20
      - uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            maven-
      - run: mvn install -Pjacoco -Dinvoker.skip
      - uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: qulice-spi/target/site/jacoco/jacoco.xml,qulice-checkstyle/target/site/jacoco/jacoco.xml,qulice-pmd/target/site/jacoco/jacoco.xml,qulice-ant/target/site/jacoco/jacoco.xml,qulice-maven-plugin/target/site/jacoco/jacoco.xml
          fail_ci_if_error: true
