# SPDX-FileCopyrightText: Copyright (c) 2011-2025 Yegor Bugayenko
# SPDX-License-Identifier: MIT
---
# yamllint disable rule:line-length
name: copyrights
'on':
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  copyrights:
    timeout-minutes: 15
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: yegor256/copyrights-action@0.0.12
        with:
          ignore: >-
            qulice-maven-plugin/src/it/pmd-violations/src/main/util/some.tex
            qulice-checkstyle/src/test/resources/com/qulice/checkstyle/**/*.java
            qulice-maven-plugin/src/it/checkstyle-violations/src/main/java/com/qulice/plugin/violations/IndentationChecks.java
